### ISSUE TITLE
Laatste 2 week to-do

### ISSUE THREAD

**Issue by Bakkertje01** [TeamSnowflake/StemApp-fieldtest#17]
Een issue met alle dingen die deze 2 week gedaan moeten worden.

Projectdocumentatie
- [ ] MTP | Justin & Kevin (wk10)
- [ ] Overdrachts document 

Handleidingen:
- [ ] Gebruikershandleiding MeApp & StemApp | Ernst-Jan (wk10)
- [ ] Gebruikershandleiding Opzetten MeApp, StemApp en koppeling | Ernst-Jan (wk10)
- [ ] Gebruikershandleiding Opzetten backend | Jimmy (wk10)

Projectmarkt
- [ ] TV | Niels v W. (wk9)
- [ ] Banner | Niels v W. (wk9)
- [ ] Powerpoint | Niels v W. (wk9)
- [ ] Monitor | Niels v W. (wk9)

Andere vakken:
- [ ] Databases 2 | Ernst-Jan (wk 9 & 10)
- [ ] Cloudfun Documentatie | Allemaal (wk9)
- [ ] SLB productenmap | Jimmy, Niels, Niels, Fekke (wk10)
- [ ] UID | Niels S. & Jimmy (wk10)

**Comment by Fekkes** [comment]
Onze omgeving moet op verzoek van de opdrachtgevers worden gepubliceerd op GitHub. Ik heb de Panel en API al op GitHub gezet. @Bakkertje01 kun jij de beide apps nog publiceren in GitHub?
