### ISSUE TITLE
Oplossing voor Stempas dispenser bedenken en ontwikkelen

### ISSUE THREAD

**Issue by Fekkes** [TeamSnowflake/StemApp-fieldtest#8]
# Oplossing voor Stempas dispenser bedenken en ontwikkelen.
Hier moeten misschien meerdere mensen aan de slag om hier een passende oplossing voor te bedenken, misschien door middel van QR-codes of tokens die uitgegeven gaan worden?
## To-Do:
- [x] Brainstormen over oplossingen
- [x] Oplossing kiezen en uitplannen
- [x] Oplossing realiseren en in de app plaatsen
- [x] ..
## Eventueel:
- [x] ..

**Comment by KevinH96** [comment]
Oplossing: IPV 2 stempassen die hardcoded toegekend worden, het aantal naar 1 aanpassen

**Comment by Fekkes** [comment]
Denk dat we dit buiten de scope van onze opdracht kunnen zien.
